### ISSUE TITLE
Using `fish_greeting` var

### ISSUE THREAD

**Issue by ghost** [laughedelic/fish_logo#1]
On iTerm 3.0 on Mac OS X:
<img width="1276" alt="screenshot 2016-06-03 17 46 18" src="https://cloud.githubusercontent.com/assets/1402084/15793628/4ab7593a-29b3-11e6-9e9e-efd1d7a4b9db.png">

Not sure if this is an issue that can be resolved, but just wanted to bring it up. I will be looking into this further. 

Love the plugin btw!

**Comment by laughedelic** [comment]
Are you using the `fish_greeting` variable? Then you should set it like this:

``` fish
begin
    set -l IFS  # otherwise newlines will be treated as array element separators
    set -U fish_greeting (fish_logo)
    set -e IFS  # this is probably not needed...
end
```

With `fish_greeting` _function_ it's not needed.

**Comment by ghost** [comment]
Was setting the variable, have converted it into a function and it works beautifully. Many thanks for the quick response 👍 !
